name: Athlon Alpha Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore athlon-alpha-be.slnx
    - name: Build
      run: dotnet build athlon-alpha-be.slnx --no-restore
    - name: Test
      run: cd athlon-alpha-be.tests
    - name: Run tests
      run: dotnet test --configuration Release --no-build
